# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XgWcl4oHrvFC_MvXYCGSDnoZKkQs4E2i
"""

import streamlit as st
import pandas as pd
import joblib

# Configuration de la page
st.set_page_config(page_title="IA Prédiction Notes", layout="wide")
st.title("🎓 Assistant IA : Optimisez votre Réussite Scolaire")

# Chargement du modèle
model = joblib.load('modele_notes.pkl')
encoders = joblib.load('encoders.pkl')

# Formulaire d'entrée
with st.sidebar:
    st.header("Mes Informations")
    study_hours = st.slider("Heures d'étude quotidiennes", 0, 10, 4)
    class_attendance = st.slider("Taux de présence (%)", 0, 100, 80)
    sleep_hours = st.slider("Heures de sommeil", 4, 12, 8)
    sleep_quality = st.selectbox("Qualité du sommeil", ["Good", "Average", "Poor"])
    exam_difficulty = st.selectbox("Difficulté de l'examen", ["Low", "Medium", "High"])
    # Ajoutez ici les autres variables selon votre dataset

# Bouton de prédiction
if st.button("Analyser mon profil"):
    # Préparation des données (on crée un DataFrame avec les noms de colonnes exacts du CSV)
    data = {
        'Hours_Studied': [study_hours],
        'Attendance': [class_attendance],
        'Sleep_Hours': [sleep_hours],
        'Sleep_Quality': [sleep_quality],
        'Exam_Difficulty': [exam_difficulty]
    }
    df_input = pd.DataFrame(data)

    # Encodage automatique
    for col, le in encoders.items():
        if col in df_input.columns:
            df_input[col] = le.transform(df_input[col])

    # Prédiction
    note_predite = model.predict(df_input)[0]

    # Affichage du résultat
    st.metric("Note estimée", f"{note_predite:.1f} / 100")

    # --- INSIGHTS ET RECOMMANDATIONS CONCRÈTES ---
    st.subheader("💡 Recommandations personnalisées")
    col1, col2 = st.columns(2)

    with col1:
        if class_attendance < 85:
            st.warning("**Assiduité :** Votre taux de présence est faible. Augmenter votre présence de 10% pourrait booster votre note.")
        if study_hours < 5:
            st.info("**Travail :** La moyenne des étudiants qui réussissent étudient plus de 5h par jour.")

    with col2:
        if sleep_hours < 7:
            st.error("**Sommeil :** Le manque de sommeil nuit à la mémorisation. Visez 8h pour stabiliser votre score.")